title: Stackbit Ampersand Theme
baseURL: /
params:
  description: Medium inspired blogging theme for Stackbit
  layout_style: grid
  palette: green
  header:
    title: pascal.brokmeier
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: About
        url: /about/
        style: link
      - label: Style Guide
        url: /style-guide/
        style: link
      - label: Contact
        url: /contact/
        style: link
  footer:
    content: '&copy; All rights reserved.'
    links:
      - label: Made with Stackbit
        url: 'https://www.stackbit.com'
        style: link
        new_window: true
    has_social: true
    social_links:
      - label: Twitter
        url: 'https://twitter.com/@PascalBrokmeier'
        style: icon
        icon_class: fa-twitter
        new_window: true
    has_subscribe: true
    subscribe_title: Subscribe for new updates
    subscribe_content: >-
      Subscribe to my email newsletter to receive useful articles and special
      offers. This monthly email is sent out on the first of every month.
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
